import { Day, Scene } from '../../../Enums';
import { SlotJSON } from '../../../Slots';

export const dimanche: SlotJSON[] = [
  {
    id: 'd-1',
    day: Day.DIMANCHE,
    startHour: 11,
    startMinute: 45,
    endHour: 12,
    endMinute: 25,
    scene: Scene.DM,
    band: 'Holy Mother',
    isOdd: true,
  },
  {
    id: 'd-2',
    day: Day.DIMANCHE,
    startHour: 13,
    startMinute: 5,
    endHour: 13,
    endMinute: 45,
    scene: Scene.DM,
    band: 'Jools',
    isOdd: false,
  },
  {
    id: 'd-3',
    day: Day.DIMANCHE,
    startHour: 14,
    startMinute: 30,
    endHour: 15,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Killers',
    isOdd: true,
  },
  {
    id: 'd-4',
    day: Day.DIMANCHE,
    startHour: 16,
    startMinute: 5,
    endHour: 16,
    endMinute: 50,
    scene: Scene.DM,
    band: 'Fit for an Autopsy',
    isOdd: false,
  },
  {
    id: 'd-5',
    day: Day.DIMANCHE,
    startHour: 17,
    startMinute: 50,
    endHour: 18,
    endMinute: 40,
    scene: Scene.DM,
    band: 'Kim Dracula',
    isOdd: true,
  },
  {
    id: 'd-6',
    day: Day.DIMANCHE,
    startHour: 19,
    startMinute: 40,
    endHour: 20,
    endMinute: 40,
    scene: Scene.DM,
    band: 'Airbourne',
    isOdd: false,
  },
  {
    id: 'd-7',
    day: Day.DIMANCHE,
    startHour: 21,
    startMinute: 40,
    endHour: 23,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Judas Priest',
    isOdd: true,
  },
  {
    id: 'd-8',
    day: Day.DIMANCHE,
    startHour: 0,
    startMinute: 10,
    endHour: 1,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Arch Enemy',
    isOdd: false,
  },

  {
    id: 'd-9',
    day: Day.DIMANCHE,
    startHour: 12,
    startMinute: 25,
    endHour: 13,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Internal Bleeding',
    isOdd: false,
  },
  {
    id: 'd-10',
    day: Day.DIMANCHE,
    startHour: 13,
    startMinute: 45,
    endHour: 14,
    endMinute: 25,
    scene: Scene.SS,
    band: 'Heavy/Hitter',
    isOdd: true,
  },
  {
    id: 'd-11',
    day: Day.DIMANCHE,
    startHour: 15,
    startMinute: 15,
    endHour: 16,
    endMinute: 0,
    scene: Scene.SS,
    band: 'Cryptopsy',
    isOdd: false,
  },
  {
    id: 'd-12',
    day: Day.DIMANCHE,
    startHour: 16,
    startMinute: 55,
    endHour: 17,
    endMinute: 45,
    scene: Scene.SS,
    band: 'Signs of the Swarm',
    isOdd: true,
  },
  {
    id: 'd-13',
    day: Day.DIMANCHE,
    startHour: 18,
    startMinute: 45,
    endHour: 19,
    endMinute: 35,
    scene: Scene.SS,
    band: 'Witch Club Satan',
    isOdd: false,
  },
  {
    id: 'd-14',
    day: Day.DIMANCHE,
    startHour: 20,
    startMinute: 45,
    endHour: 21,
    endMinute: 35,
    scene: Scene.SS,
    band: 'Vader',
    isOdd: true,
  },
  {
    id: 'd-15',
    day: Day.DIMANCHE,
    startHour: 23,
    startMinute: 15,
    endHour: 0,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Sacred Reich',
    isOdd: false,
  },

  {
    id: 'd-16',
    day: Day.DIMANCHE,
    startHour: 12,
    startMinute: 25,
    endHour: 13,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Eyes',
    isOdd: true,
  },
  {
    id: 'd-17',
    day: Day.DIMANCHE,
    startHour: 13,
    startMinute: 45,
    endHour: 14,
    endMinute: 25,
    scene: Scene.MF,
    band: 'Heretoir',
    isOdd: false,
  },
  {
    id: 'd-18',
    day: Day.DIMANCHE,
    startHour: 15,
    startMinute: 15,
    endHour: 16,
    endMinute: 0,
    scene: Scene.MF,
    band: 'Pain Magazine',
    isOdd: true,
  },
  {
    id: 'd-19',
    day: Day.DIMANCHE,
    startHour: 16,
    startMinute: 55,
    endHour: 17,
    endMinute: 45,
    scene: Scene.MF,
    band: 'John Cxnnor',
    isOdd: false,
  },
  {
    id: 'd-20',
    day: Day.DIMANCHE,
    startHour: 18,
    startMinute: 45,
    endHour: 19,
    endMinute: 35,
    scene: Scene.MF,
    band: 'Voivod',
    isOdd: true,
  },
  {
    id: 'd-21',
    day: Day.DIMANCHE,
    startHour: 20,
    startMinute: 45,
    endHour: 21,
    endMinute: 35,
    scene: Scene.MF,
    band: 'Deafheaven',
    isOdd: false,
  },
  {
    id: 'd-22',
    day: Day.DIMANCHE,
    startHour: 23,
    startMinute: 15,
    endHour: 0,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Shaârghot',
    isOdd: true,
  },

  {
    id: 'd-23',
    day: Day.DIMANCHE,
    startHour: 11,
    startMinute: 45,
    endHour: 12,
    endMinute: 25,
    scene: Scene.BD,
    band: 'Les Hommes Crabes',
    isOdd: true,
  },
  {
    id: 'd-24',
    day: Day.DIMANCHE,
    startHour: 13,
    startMinute: 5,
    endHour: 13,
    endMinute: 45,
    scene: Scene.BD,
    band: 'Modder',
    isOdd: false,
  },
  {
    id: 'd-25',
    day: Day.DIMANCHE,
    startHour: 14,
    startMinute: 30,
    endHour: 15,
    endMinute: 10,
    scene: Scene.BD,
    band: 'Red Sun Atacama',
    isOdd: true,
  },
  {
    id: 'd-26',
    day: Day.DIMANCHE,
    startHour: 16,
    startMinute: 5,
    endHour: 16,
    endMinute: 50,
    scene: Scene.BD,
    band: 'Wormsand',
    isOdd: false,
  },
  {
    id: 'd-27',
    day: Day.DIMANCHE,
    startHour: 17,
    startMinute: 50,
    endHour: 18,
    endMinute: 40,
    scene: Scene.BD,
    band: 'Castle Rat',
    isOdd: true,
  },
  {
    id: 'd-28',
    day: Day.DIMANCHE,
    startHour: 19,
    startMinute: 40,
    endHour: 20,
    endMinute: 40,
    scene: Scene.BD,
    band: 'Monkeys on Mars',
    isOdd: false,
  },
  {
    id: 'd-29',
    day: Day.DIMANCHE,
    startHour: 21,
    startMinute: 40,
    endHour: 23,
    endMinute: 10,
    scene: Scene.BD,
    band: 'Coltaine',
    isOdd: true,
  },
  {
    id: 'd-30',
    day: Day.DIMANCHE,
    startHour: 0,
    startMinute: 10,
    endHour: 1,
    endMinute: 10,
    scene: Scene.BD,
    band: 'Warning',
    isOdd: false,
  },
];
