import { Day, Scene } from '../../../Enums';
import { SlotJSON } from '../../../Slots';

export const jeudi: any = [{
  id: 'j-1',
  day: Day.JEUDI,
  startHour: 15,
  startMinute: 15,
  endHour: 16,
  endMinute: 0,
  scene: Scene.DM,
  band: 'Unearth',
  isOdd: true,
},
{
  id: 'j-2',
  day: Day.JEUDI,
  startHour: 16,
  startMinute: 50,
  endHour: 17,
  endMinute: 50,
  scene: Scene.DM,
  band: 'Kittie',
  isOdd: false,
},
{
  id: 'j-3',
  day: Day.JEUDI,
  startHour: 18,
  startMinute: 50,
  endHour: 19,
  endMinute: 50,
  scene: Scene.DM,
  band: 'TBC',
  isOdd: true,
},
{
  id: 'j-4',
  day: Day.JEUDI,
  startHour: 20,
  startMinute: 55,
  endHour: 22,
  endMinute: 5,
  scene: Scene.DM,
  band: 'Godsmack',
  isOdd: false,
},
{
  id: 'j-5',
  day: Day.JEUDI,
  startHour: 23,
  startMinute: 15,
  endHour: 0,
  endMinute: 25,
  scene: Scene.DM,
  band: 'Primus',
  isOdd: true,
},
{
  id: 'j-6',
  day: Day.JEUDI,
  startHour: 16,
  startMinute: 5,
  endHour: 16,
  endMinute: 45,
  scene: Scene.MF,
  band: 'Battlesnake',
  isOdd: true,
},
{
  id: 'j-7',
  day: Day.JEUDI,
  startHour: 17,
  startMinute: 55,
  endHour: 18,
  endMinute: 45,
  scene: Scene.MF,
  band: 'Pilori',
  isOdd: false,
},
{
  id: 'j-8',
  day: Day.JEUDI,
  startHour: 19,
  startMinute: 50,
  endHour: 20,
  endMinute: 50,
  scene: Scene.MF,
  band: 'Gaerea',
  isOdd: true,
},
{
  id: 'j-9',
  day: Day.JEUDI,
  startHour: 22,
  startMinute: 10,
  endHour: 23,
  endMinute: 10,
  scene: Scene.MF,
  band: 'Amenra',
  isOdd: false,
},
{
  id: 'j-10',
  day: Day.JEUDI,
  startHour: 0,
  startMinute: 30,
  endHour: 1,
  endMinute: 30,
  scene: Scene.MF,
  band: 'Oomph!',
  isOdd: true,
},
{
  id: 'j-11',
  day: Day.JEUDI,
  startHour: 16,
  startMinute: 5,
  endHour: 16,
  endMinute: 45,
  scene: Scene.SS,
  band: '200 Stab Wounds',
  isOdd: false,
},
{
  id: 'j-12',
  day: Day.JEUDI,
  startHour: 17,
  startMinute: 55,
  endHour: 18,
  endMinute: 45,
  scene: Scene.SS,
  band: 'Sanguisugabogg',
  isOdd: true,
},
{
  id: 'j-13',
  day: Day.JEUDI,
  startHour: 19,
  startMinute: 50,
  endHour: 20,
  endMinute: 50,
  scene: Scene.SS,
  band: 'Bloodbath',
  isOdd: false,
},
{
  id: 'j-14',
  day: Day.JEUDI,
  startHour: 22,
  startMinute: 10,
  endHour: 23,
  endMinute: 10,
  scene: Scene.SS,
  band: 'Death Angel',
  isOdd: true,
},
{
  id: 'j-15',
  day: Day.JEUDI,
  startHour: 0,
  startMinute: 30,
  endHour: 1,
  endMinute: 30,
  scene: Scene.SS,
  band: 'Municipal Waste',
  isOdd: false,
},
{
  id: 'j-16',
  day: Day.JEUDI,
  startHour: 15,
  startMinute: 15,
  endHour: 16,
  endMinute: 0,
  scene: Scene.BD,
  band: 'Fauxx',
  isOdd: false,
},
{
  id: 'j-17',
  day: Day.JEUDI,
  startHour: 16,
  startMinute: 50,
  endHour: 17,
  endMinute: 50,
  scene: Scene.BD,
  band: 'Brieg Guerveno',
  isOdd: true,
},
{
  id: 'j-18',
  day: Day.JEUDI,
  startHour: 18,
  startMinute: 50,
  endHour: 19,
  endMinute: 50,
  scene: Scene.BD,
  band: 'Celkilt x Bagad de Quimper',
  isOdd: false,
},
{
  id: 'j-19',
  day: Day.JEUDI,
  startHour: 20,
  startMinute: 55,
  endHour: 22,
  endMinute: 5,
  scene: Scene.BD,
  band: 'Denez Prigent',
  isOdd: true,
},
{
  id: 'j-20',
  day: Day.JEUDI,
  startHour: 23,
  startMinute: 15,
  endHour: 0,
  endMinute: 25,
  scene: Scene.BD,
  band: 'Komodrag and the Mounodor',
  isOdd: false,
},]