

import { Day, Scene } from '../../../Enums';
import { SlotJSON } from '../../../Slots';

export const samedi: SlotJSON[] = [
  {
    id: 's-1',
    day: Day.SAMEDI,
    startHour: 12,
    startMinute: 45,
    endHour: 13,
    endMinute: 25,
    scene: Scene.DM,
    band: 'Necrowretch',
    isOdd: true,
  },
  {
    id: 's-2',
    day: Day.SAMEDI,
    startHour: 14,
    startMinute: 15,
    endHour: 14,
    endMinute: 55,
    scene: Scene.DM,
    band: 'Ashen',
    isOdd: false,
  },
  {
    id: 's-3',
    day: Day.SAMEDI,
    startHour: 15,
    startMinute: 45,
    endHour: 16,
    endMinute: 30,
    scene: Scene.DM,
    band: 'Sidilarsen',
    isOdd: true,
  },
  {
    id: 's-4',
    day: Day.SAMEDI,
    startHour: 17,
    startMinute: 25,
    endHour: 18,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Orden Ogan',
    isOdd: false,
  },
  {
    id: 's-5',
    day: Day.SAMEDI,
    startHour: 19,
    startMinute: 10,
    endHour: 20,
    endMinute: 0,
    scene: Scene.DM,
    band: 'Leprous',
    isOdd: true,
  },
  {
    id: 's-6',
    day: Day.SAMEDI,
    startHour: 21,
    startMinute: 0,
    endHour: 22,
    endMinute: 0,
    scene: Scene.DM,
    band: 'Eisbrecher',
    isOdd: false,
  },
  {
    id: 's-7',
    day: Day.SAMEDI,
    startHour: 23,
    startMinute: 0,
    endHour: 0,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Within Temptation',
    isOdd: true,
  },
  {
    id: 's-8',
    day: Day.SAMEDI,
    startHour: 1,
    startMinute: 30,
    endHour: 2,
    endMinute: 30,
    scene: Scene.DM,
    band: 'Perturbator',
    isOdd: false,
  },

  {
    id: 's-9',
    day: Day.SAMEDI,
    startHour: 13,
    startMinute: 30,
    endHour: 14,
    endMinute: 10,
    scene: Scene.SS,
    band: 'Aorlhac',
    isOdd: false,
  },
  {
    id: 's-10',
    day: Day.SAMEDI,
    startHour: 15,
    startMinute: 0,
    endHour: 15,
    endMinute: 40,
    scene: Scene.SS,
    band: 'Rectal Smegma',
    isOdd: true,
  },
  {
    id: 's-11',
    day: Day.SAMEDI,
    startHour: 16,
    startMinute: 35,
    endHour: 17,
    endMinute: 20,
    scene: Scene.SS,
    band: 'Cancer',
    isOdd: false,
  },
  {
    id: 's-12',
    day: Day.SAMEDI,
    startHour: 18,
    startMinute: 15,
    endHour: 19,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Grave',
    isOdd: true,
  },
  {
    id: 's-13',
    day: Day.SAMEDI,
    startHour: 20,
    startMinute: 5,
    endHour: 20,
    endMinute: 55,
    scene: Scene.SS,
    band: 'Anaal Nathrakh',
    isOdd: false,
  },
  {
    id: 's-14',
    day: Day.SAMEDI,
    startHour: 22,
    startMinute: 15,
    endHour: 23,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Nevermore',
    isOdd: true,
  },
  {
    id: 's-15',
    day: Day.SAMEDI,
    startHour: 0,
    startMinute: 25,
    endHour: 1,
    endMinute: 25,
    scene: Scene.SS,
    band: 'Omnium Gatherum',
    isOdd: false,
  },

  {
    id: 's-16',
    day: Day.SAMEDI,
    startHour: 13,
    startMinute: 30,
    endHour: 14,
    endMinute: 10,
    scene: Scene.MF,
    band: 'Basalt',
    isOdd: true,
  },
  {
    id: 's-17',
    day: Day.SAMEDI,
    startHour: 15,
    startMinute: 0,
    endHour: 15,
    endMinute: 40,
    scene: Scene.MF,
    band: 'Bruit ≤',
    isOdd: false,
  },
  {
    id: 's-18',
    day: Day.SAMEDI,
    startHour: 16,
    startMinute: 35,
    endHour: 17,
    endMinute: 20,
    scene: Scene.MF,
    band: 'Hollow Jan',
    isOdd: true,
  },
  {
    id: 's-19',
    day: Day.SAMEDI,
    startHour: 18,
    startMinute: 15,
    endHour: 19,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Múr',
    isOdd: false,
  },
  {
    id: 's-20',
    day: Day.SAMEDI,
    startHour: 20,
    startMinute: 5,
    endHour: 20,
    endMinute: 55,
    scene: Scene.MF,
    band: 'Slift',
    isOdd: true,
  },
  {
    id: 's-21',
    day: Day.SAMEDI,
    startHour: 22,
    startMinute: 15,
    endHour: 23,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Svinkels Friends & Family',
    isOdd: false,
  },
  {
    id: 's-22',
    day: Day.SAMEDI,
    startHour: 0,
    startMinute: 25,
    endHour: 1,
    endMinute: 25,
    scene: Scene.MF,
    band: 'Sierra Veins',
    isOdd: true,
  },

  {
    id: 's-23',
    day: Day.SAMEDI,
    startHour: 12,
    startMinute: 45,
    endHour: 13,
    endMinute: 25,
    scene: Scene.BD,
    band: 'Shady Fat Katz',
    isOdd: true,
  },
  {
    id: 's-24',
    day: Day.SAMEDI,
    startHour: 14,
    startMinute: 15,
    endHour: 14,
    endMinute: 55,
    scene: Scene.BD,
    band: 'Monde de Merde',
    isOdd: false,
  },
  {
    id: 's-25',
    day: Day.SAMEDI,
    startHour: 15,
    startMinute: 45,
    endHour: 16,
    endMinute: 30,
    scene: Scene.BD,
    band: 'Jetsex',
    isOdd: true,
  },
  {
    id: 's-26',
    day: Day.SAMEDI,
    startHour: 17,
    startMinute: 25,
    endHour: 18,
    endMinute: 10,
    scene: Scene.BD,
    band: 'The Casualties',
    isOdd: false,
  },
  {
    id: 's-27',
    day: Day.SAMEDI,
    startHour: 19,
    startMinute: 10,
    endHour: 20,
    endMinute: 0,
    scene: Scene.BD,
    band: 'Les 3 Fromages',
    isOdd: true,
  },
  {
    id: 's-28',
    day: Day.SAMEDI,
    startHour: 21,
    startMinute: 0,
    endHour: 22,
    endMinute: 0,
    scene: Scene.BD,
    band: 'Frog Leap',
    isOdd: false,
  },
  {
    id: 's-29',
    day: Day.SAMEDI,
    startHour: 23,
    startMinute: 10,
    endHour: 0,
    endMinute: 20,
    scene: Scene.BD,
    band: 'Steven’n’Seagulls',
    isOdd: true,
  },
  {
    id: 's-30',
    day: Day.SAMEDI,
    startHour: 1,
    startMinute: 30,
    endHour: 2,
    endMinute: 30,
    scene: Scene.BD,
    band: 'Nanowar of Steel',
    isOdd: false,
  },
];