import { Day, Scene } from '../../../Enums';
import { SlotJSON } from '../../../Slots';

export const vendredi: SlotJSON[] = [
  {
    id: 'v-1',
    day: Day.VENDREDI,
    startHour: 12,
    startMinute: 45,
    endHour: 13,
    endMinute: 25,
    scene: Scene.DM,
    band: 'Ice Sealed Eyes',
    isOdd: true,
  },
  {
    id: 'v-2',
    day: Day.VENDREDI,
    startHour: 14,
    startMinute: 15,
    endHour: 14,
    endMinute: 55,
    scene: Scene.DM,
    band: 'Cage Fight',
    isOdd: false,
  },
  {
    id: 'v-3',
    day: Day.VENDREDI,
    startHour: 15,
    startMinute: 45,
    endHour: 16,
    endMinute: 30,
    scene: Scene.DM,
    band: 'Hellripper',
    isOdd: true,
  },
  {
    id: 'v-4',
    day: Day.VENDREDI,
    startHour: 17,
    startMinute: 25,
    endHour: 18,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Chelsea Grin',
    isOdd: false,
  },
  {
    id: 'v-5',
    day: Day.VENDREDI,
    startHour: 19,
    startMinute: 10,
    endHour: 20,
    endMinute: 0,
    scene: Scene.DM,
    band: 'Lord of the Lost',
    isOdd: true,
  },
  {
    id: 'v-6',
    day: Day.VENDREDI,
    startHour: 21,
    startMinute: 0,
    endHour: 22,
    endMinute: 0,
    scene: Scene.DM,
    band: 'Mass Hysteria',
    isOdd: false,
  },
  {
    id: 'v-7',
    day: Day.VENDREDI,
    startHour: 23,
    startMinute: 0,
    endHour: 0,
    endMinute: 10,
    scene: Scene.DM,
    band: 'Slaughter to Prevail',
    isOdd: true,
  },
  {
    id: 'v-8',
    day: Day.VENDREDI,
    startHour: 1,
    startMinute: 20,
    endHour: 2,
    endMinute: 20,
    scene: Scene.DM,
    band: 'Filth',
    isOdd: false,
  },

  {
    id: 'v-9',
    day: Day.VENDREDI,
    startHour: 13,
    startMinute: 30,
    endHour: 14,
    endMinute: 10,
    scene: Scene.SS,
    band: 'Guineapig',
    isOdd: false,
  },
  {
    id: 'v-10',
    day: Day.VENDREDI,
    startHour: 15,
    startMinute: 0,
    endHour: 15,
    endMinute: 40,
    scene: Scene.SS,
    band: 'Skaphos',
    isOdd: true,
  },
  {
    id: 'v-11',
    day: Day.VENDREDI,
    startHour: 16,
    startMinute: 35,
    endHour: 17,
    endMinute: 20,
    scene: Scene.SS,
    band: 'Bölzer',
    isOdd: false,
  },
  {
    id: 'v-12',
    day: Day.VENDREDI,
    startHour: 18,
    startMinute: 15,
    endHour: 19,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Coroner',
    isOdd: true,
  },
  {
    id: 'v-13',
    day: Day.VENDREDI,
    startHour: 20,
    startMinute: 5,
    endHour: 20,
    endMinute: 55,
    scene: Scene.SS,
    band: 'Unleashed',
    isOdd: false,
  },
  {
    id: 'v-14',
    day: Day.VENDREDI,
    startHour: 22,
    startMinute: 5,
    endHour: 23,
    endMinute: 5,
    scene: Scene.SS,
    band: 'Emperor',
    isOdd: true,
  },
  {
    id: 'v-15',
    day: Day.VENDREDI,
    startHour: 0,
    startMinute: 15,
    endHour: 1,
    endMinute: 15,
    scene: Scene.SS,
    band: 'Darkened Nocturn Slaughtercult',
    isOdd: false,
  },

  {
    id: 'v-16',
    day: Day.VENDREDI,
    startHour: 13,
    startMinute: 30,
    endHour: 14,
    endMinute: 10,
    scene: Scene.MF,
    band: 'Gravity',
    isOdd: true,
  },
  {
    id: 'v-17',
    day: Day.VENDREDI,
    startHour: 15,
    startMinute: 0,
    endHour: 15,
    endMinute: 40,
    scene: Scene.MF,
    band: 'Urne',
    isOdd: false,
  },
  {
    id: 'v-18',
    day: Day.VENDREDI,
    startHour: 16,
    startMinute: 35,
    endHour: 17,
    endMinute: 20,
    scene: Scene.MF,
    band: 'Iotunn',
    isOdd: true,
  },
  {
    id: 'v-19',
    day: Day.VENDREDI,
    startHour: 18,
    startMinute: 15,
    endHour: 19,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Textures',
    isOdd: false,
  },
  {
    id: 'v-20',
    day: Day.VENDREDI,
    startHour: 20,
    startMinute: 5,
    endHour: 20,
    endMinute: 55,
    scene: Scene.MF,
    band: 'Soen',
    isOdd: true,
  },
  {
    id: 'v-21',
    day: Day.VENDREDI,
    startHour: 22,
    startMinute: 5,
    endHour: 23,
    endMinute: 5,
    scene: Scene.MF,
    band: 'Paradise Lost',
    isOdd: false,
  },
  {
    id: 'v-22',
    day: Day.VENDREDI,
    startHour: 0,
    startMinute: 15,
    endHour: 1,
    endMinute: 15,
    scene: Scene.MF,
    band: 'Alcest',
    isOdd: true,
  },

  {
    id: 'v-23',
    day: Day.VENDREDI,
    startHour: 12,
    startMinute: 45,
    endHour: 13,
    endMinute: 25,
    scene: Scene.BD,
    band: 'Nawather',
    isOdd: true,
  },
  {
    id: 'v-24',
    day: Day.VENDREDI,
    startHour: 14,
    startMinute: 15,
    endHour: 14,
    endMinute: 55,
    scene: Scene.BD,
    band: 'Vansind',
    isOdd: false,
  },
  {
    id: 'v-25',
    day: Day.VENDREDI,
    startHour: 15,
    startMinute: 45,
    endHour: 16,
    endMinute: 30,
    scene: Scene.BD,
    band: 'Stille Volk',
    isOdd: true,
  },
  {
    id: 'v-26',
    day: Day.VENDREDI,
    startHour: 17,
    startMinute: 25,
    endHour: 18,
    endMinute: 10,
    scene: Scene.BD,
    band: 'Hrafngrimr',
    isOdd: false,
  },
  {
    id: 'v-27',
    day: Day.VENDREDI,
    startHour: 19,
    startMinute: 10,
    endHour: 20,
    endMinute: 0,
    scene: Scene.BD,
    band: 'Miracle of Sound',
    isOdd: true,
  },
  {
    id: 'v-28',
    day: Day.VENDREDI,
    startHour: 21,
    startMinute: 0,
    endHour: 22,
    endMinute: 0,
    scene: Scene.BD,
    band: 'Visions of Atlantis',
    isOdd: false,
  },
  {
    id: 'v-29',
    day: Day.VENDREDI,
    startHour: 23,
    startMinute: 0,
    endHour: 0,
    endMinute: 10,
    scene: Scene.BD,
    band: 'Master Boot Record',
    isOdd: true,
  },
  {
    id: 'v-30',
    day: Day.VENDREDI,
    startHour: 1,
    startMinute: 20,
    endHour: 2,
    endMinute: 20,
    scene: Scene.BD,
    band: 'Eihwar',
    isOdd: false,
  },
];
